# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d182659eceaaea5f1e50a07648b64fdf5e048c4c544a7625cd854afb3548ff6c6001240f0927d2776b9a99b829883d097718c601afefb62ab6edf94d78159d0c

test:
  secret_key_base: b3b47de0dd9a597a3d0c473b70981e8dccd1a162c38efaf353dbabf4e64e7cd85b9357429dc4128185f7b4fd182a392e70777ec7a038ba5f3b847e9125965224

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
